### ISSUE TITLE
taxregistrations.py coto dependency broken

### ISSUE THREAD

**Issue by wcarlsen** [dfds/prime-pipeline-docker#2]
Coto dependecy broken: https://github.com/sentialabs/coto

Cannot set tax settings from TaxRegistration Dict according to coto documentation.

Error return from put request:
Exception: failed put taxexemption/eu/vat/information: {"message":"SetTaxRegistration","type":"BPCValidationException","errorCode":"","constraintViolationCodeList":[]}

**Comment by wcarlsen** [comment]
I have created an issue on coto project https://github.com/sentialabs/coto/issues/6

**Comment by HenrikStanley** [comment]
We have decided to work around the issue by manually updating the tax settings in AWS for now.
In the long, Amazon has told us they will enable inheritance from the master account solving our issue.
